name: .NET CI

on:
  workflow_call:
    inputs:
      artifactPath:
        description: 'Path to save build artifacts'
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '6.0.x'

      - name: Restore dependencies
        run: dotnet restore myconsoleapp/myconsoleapp.csproj

      - name: Build
        run: dotnet build myconsoleapp/myconsoleapp.csproj --no-restore

      - name: Test
        run: dotnet test myconsoleapp/myconsoleapp.csproj --no-build --verbosity normal

      - name: Publish
        run: dotnet publish myconsoleapp/myconsoleapp.csproj --no-build -o ${{ inputs.artifactPath }}

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Build-artifacts
          path: ${{ inputs.artifactPath }}
